function [Previously_Defined_Material_out] = Creat_Permittivity_Sector(fid, Box_Number_String, r, phi_deg, dr, dphi_deg, Zsize, Permittivity, Quantization_Levels_Vec, Previously_Defined_Material_in, Loss_Tangent, Teeth_T)

% dphi_deg = round(dphi_deg * 1000) / 1000;

Ypos1 = (r - 0.5*dr) * sind(phi_deg - 0.5*dphi_deg);
Zpos1 = (r - 0.5*dr) * cosd(phi_deg - 0.5*dphi_deg);

Ypos2 = (r + 0.5*dr) * sind(phi_deg - 0.5*dphi_deg);
Zpos2 = (r + 0.5*dr) * cosd(phi_deg - 0.5*dphi_deg);

% Ypos3 = (r - 0.5*dr) * sind(phi_deg + 0.5*dphi_deg);
% Zpos3 = (r - 0.5*dr) * cosd(phi_deg + 0.5*dphi_deg);

% Ypos3 = Ypos1 * cosd(dphi_deg/2) - Zpos1 * sind(dphi_deg/2);
% Zpos3 = Ypos1 * sind(dphi_deg/2) + Zpos1 * cosd(dphi_deg/2);

Ypos3 = (r - 0.5*dr) * sind(phi_deg - ((1 - Teeth_T)/2) * dphi_deg);
Zpos3 = (r - 0.5*dr) * cosd(phi_deg - ((1 - Teeth_T)/2) * dphi_deg);

% Ypos4 = (r + 0.5*dr) * sind(phi_deg + 0.5*dphi_deg);
% Zpos4 = (r + 0.5*dr) * cosd(phi_deg + 0.5*dphi_deg);

% Ypos4 = Ypos2 * cosd(dphi_deg/2) - Zpos2 * sind(dphi_deg/2);
% Zpos4 = Ypos2 * sind(dphi_deg/2) + Zpos2 * cosd(dphi_deg/2);

Ypos4 = (r + 0.5*dr) * sind(phi_deg - ((1 - Teeth_T)/2) * dphi_deg);
Zpos4 = (r + 0.5*dr) * cosd(phi_deg - ((1 - Teeth_T)/2) * dphi_deg);

% Ypos5 = Ypos1 * cosd(dphi_deg) - Zpos1 * sind(dphi_deg);
% Zpos5 = Ypos1 * sind(dphi_deg) + Zpos1 * cosd(dphi_deg);

Ypos5 = (r - 0.5*dr) * sind(phi_deg + (0.5 + (Teeth_T - 1)) * dphi_deg);
Zpos5 = (r - 0.5*dr) * cosd(phi_deg + (0.5 + (Teeth_T - 1)) * dphi_deg);

% Ypos6 = Ypos2 * cosd(dphi_deg) - Zpos2 * sind(dphi_deg);
% Zpos6 = Ypos2 * sind(dphi_deg) + Zpos2 * cosd(dphi_deg);

Ypos6 = (r + 0.5*dr) * sind(phi_deg + (0.5 + (Teeth_T - 1)) * dphi_deg);
Zpos6 = (r + 0.5*dr) * cosd(phi_deg + (0.5 + (Teeth_T - 1)) * dphi_deg);

Ypos1_mm_string = num2str(Ypos1 * 1000);
Ypos2_mm_string = num2str(Ypos2 * 1000);
Zpos1_mm_string = num2str(Zpos1 * 1000);
Zpos2_mm_string = num2str(Zpos2 * 1000);

Ypos3_mm_string = num2str(Ypos3 * 1000);
Ypos4_mm_string = num2str(Ypos4 * 1000);
Zpos3_mm_string = num2str(Zpos3 * 1000);
Zpos4_mm_string = num2str(Zpos4 * 1000);

Ypos5_mm_string = num2str(Ypos5 * 1000);
Ypos6_mm_string = num2str(Ypos6 * 1000);
Zpos5_mm_string = num2str(Zpos5 * 1000);
Zpos6_mm_string = num2str(Zpos6 * 1000);


c = turbo(numel(Quantization_Levels_Vec));

% idx = find(Quantization_Levels_Vec == Permittivity);
[~, idx] = min(abs(Quantization_Levels_Vec - Permittivity));

%idx

cii1 = num2str( floor( c( idx, 1 ) .* 255 ) );
cii2 = num2str( floor( c( idx, 2 ) .* 255 ) );
cii3 = num2str( floor( c( idx, 3 ) .* 255 ) );



% fprintf( fid, 'oEditor.CreatePolyline(\n');
% fprintf( fid, '	[\n');
% fprintf( fid, '		"NAME:PolylineParameters",\n');
% fprintf( fid, '		"IsPolylineCovered:="	, True,\n');
% fprintf( fid, '		"IsPolylineClosed:="	, False,\n');
% fprintf( fid, '		[\n');
% fprintf( fid, '			"NAME:PolylinePoints",\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLPoint",\n');
% fprintf( fid, '				"X:="			, "0mm",\n');
% fprintf( fid, ['				"Y:="			, "', Ypos1_mm_string, 'mm",\n']);
% fprintf( fid, ['				"Z:="			, "', Zpos1_mm_string, 'mm"\n']);
% fprintf( fid, '			],\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLPoint",\n');
% fprintf( fid, '				"X:="			, "0mm",\n');
% fprintf( fid, ['				"Y:="			, "', Ypos3_mm_string, 'mm",\n']);
% fprintf( fid, ['				"Z:="			, "', Zpos3_mm_string, 'mm"\n']);
% fprintf( fid, '			],\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLPoint",\n');
% fprintf( fid, '				"X:="			, "0mm",\n');
% fprintf( fid, ['				"Y:="			, "', Ypos5_mm_string, 'mm",\n']);
% fprintf( fid, ['				"Z:="			, "', Zpos5_mm_string, 'mm"\n']);
% fprintf( fid, '			]\n');
% fprintf( fid, '		],\n');
% fprintf( fid, '		[\n');
% fprintf( fid, '			"NAME:PolylineSegments",\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLSegment",\n');
% fprintf( fid, '				"SegmentType:="		, "AngularArc",\n');
% fprintf( fid, '				"StartIndex:="		, 0,\n');
% fprintf( fid, '				"NoOfPoints:="		, 3,\n');
% fprintf( fid, '				"NoOfSegments:="	, "0",\n');
% fprintf( fid, ['				"ArcAngle:="		, "', num2str(dphi_deg) ,'deg",\n']);
% fprintf( fid, '				"ArcCenterX:="		, "0mm",\n');
% fprintf( fid, '				"ArcCenterY:="		, "0mm",\n');
% fprintf( fid, '				"ArcCenterZ:="		, "0mm",\n');
% fprintf( fid, '				"ArcPlane:="		, "YZ"\n');
% fprintf( fid, '			]\n');
% fprintf( fid, '		],\n');
% fprintf( fid, '		[\n');
% fprintf( fid, '			"NAME:PolylineXSection",\n');
% fprintf( fid, '			"XSectionType:="	, "None",\n');
% fprintf( fid, '			"XSectionOrient:="	, "Auto",\n');
% fprintf( fid, '			"XSectionWidth:="	, "0mm",\n');
% fprintf( fid, '			"XSectionTopWidth:="	, "0mm",\n');
% fprintf( fid, '			"XSectionHeight:="	, "0mm",\n');
% fprintf( fid, '			"XSectionNumSegments:="	, "0",\n');
% fprintf( fid, '			"XSectionBendType:="	, "Corner"\n');
% fprintf( fid, '		]\n');
% fprintf( fid, '	], \n');
% fprintf( fid, '	[\n');
% fprintf( fid, '		"NAME:Attributes",\n');
% fprintf( fid, ['		"Name:="		, "Polyline1_', Box_Number_String, '",\n']);
% fprintf( fid, '		"Flags:="		, "",\n');
% fprintf( fid, '		"Color:="		, "(143 175 143)",\n');
% fprintf( fid, '		"Transparency:="	, 0,\n');
% fprintf( fid, '		"PartCoordinateSystem:=", "Global",\n');
% fprintf( fid, '		"UDMId:="		, "",\n');
% fprintf( fid, '		"MaterialValue:="	, "\\"vacuum\\"",\n');
% fprintf( fid, '		"SurfaceMaterialValue:=", "\\"\\"",\n');
% fprintf( fid, '		"SolveInside:="		, True,\n');
% fprintf( fid, '		"ShellElement:="	, False,\n');
% fprintf( fid, '		"ShellElementThickness:=", "0mm",\n');
% fprintf( fid, '		"ReferenceTemperature:=", "20cel",\n');
% fprintf( fid, '		"IsMaterialEditable:="	, True,\n');
% fprintf( fid, '		"IsSurfaceMaterialEditable:=", True,\n');
% fprintf( fid, '		"UseMaterialAppearance:=", False,\n');
% fprintf( fid, '		"IsLightweight:="	, False\n');
% fprintf( fid, '	])\n');


fprintf( fid, 'oEditor.CreatePolyline(\n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:PolylineParameters",\n');
fprintf( fid, '		"IsPolylineCovered:="	, True,\n');
fprintf( fid, '		"IsPolylineClosed:="	, False,\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:PolylinePoints",\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLPoint",\n');
fprintf( fid, '				"X:="			, "0mm",\n');
fprintf( fid, ['				"Y:="			, "', Ypos1_mm_string, 'mm",\n']);
fprintf( fid, ['				"Z:="			, "', Zpos1_mm_string, 'mm"\n']);
fprintf( fid, '			],\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLPoint",\n');
fprintf( fid, '				"X:="			, "0mm",\n');
fprintf( fid, ['				"Y:="			, "', Ypos3_mm_string, 'mm",\n']);
fprintf( fid, ['				"Z:="			, "', Zpos3_mm_string, 'mm"\n']);
fprintf( fid, '			],\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLPoint",\n');
fprintf( fid, '				"X:="			, "0mm",\n');
fprintf( fid, ['				"Y:="			, "', Ypos5_mm_string, 'mm",\n']);
fprintf( fid, ['				"Z:="			, "', Zpos5_mm_string, 'mm"\n']);
fprintf( fid, '			]\n');
fprintf( fid, '		],\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:PolylineSegments",\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLSegment",\n');
fprintf( fid, '				"SegmentType:="		, "Arc",\n');
fprintf( fid, '				"StartIndex:="		, 0,\n');
fprintf( fid, '				"NoOfPoints:="		, 3,\n');
fprintf( fid, '				"NoOfSegments:="	, "0"\n');
fprintf( fid, '			]\n');
fprintf( fid, '		],\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:PolylineXSection",\n');
fprintf( fid, '			"XSectionType:="	, "None",\n');
fprintf( fid, '			"XSectionOrient:="	, "Auto",\n');
fprintf( fid, '			"XSectionWidth:="	, "0mm",\n');
fprintf( fid, '			"XSectionTopWidth:="	, "0mm",\n');
fprintf( fid, '			"XSectionHeight:="	, "0mm",\n');
fprintf( fid, '			"XSectionNumSegments:="	, "0",\n');
fprintf( fid, '			"XSectionBendType:="	, "Corner"\n');
fprintf( fid, '		]\n');
fprintf( fid, '	], \n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:Attributes",\n');
fprintf( fid, ['		"Name:="		, "Polyline1_', Box_Number_String, '",\n']);
fprintf( fid, '		"Flags:="		, "",\n');
fprintf( fid, '		"Color:="		, "(143 175 143)",\n');
fprintf( fid, '		"Transparency:="	, 0,\n');
fprintf( fid, '		"PartCoordinateSystem:=", "Global",\n');
fprintf( fid, '		"UDMId:="		, "",\n');
fprintf( fid, '		"MaterialValue:="	, "\\"vacuum\\"",\n');
fprintf( fid, '		"SurfaceMaterialValue:=", "\\"\\"",\n');
fprintf( fid, '		"SolveInside:="		, True,\n');
fprintf( fid, '		"ShellElement:="	, False,\n');
fprintf( fid, '		"ShellElementThickness:=", "0mm",\n');
fprintf( fid, '		"ReferenceTemperature:=", "20cel",\n');
fprintf( fid, '		"IsMaterialEditable:="	, True,\n');
fprintf( fid, '		"IsSurfaceMaterialEditable:=", True,\n');
fprintf( fid, '		"UseMaterialAppearance:=", False,\n');
fprintf( fid, '		"IsLightweight:="	, False\n');
fprintf( fid, '	])\n');



% fprintf( fid, 'oEditor.CreatePolyline(\n');
% fprintf( fid, '	[\n');
% fprintf( fid, '		"NAME:PolylineParameters",\n');
% fprintf( fid, '		"IsPolylineCovered:="	, True,\n');
% fprintf( fid, '		"IsPolylineClosed:="	, False,\n');
% fprintf( fid, '		[\n');
% fprintf( fid, '			"NAME:PolylinePoints",\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLPoint",\n');
% fprintf( fid, '				"X:="			, "0mm",\n');
% fprintf( fid, ['				"Y:="			, "', Ypos1_mm_string, 'mm",\n']);
% fprintf( fid, ['				"Z:="			, "', Zpos1_mm_string, 'mm"\n']);
% fprintf( fid, '			],\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLPoint",\n');
% fprintf( fid, '				"X:="			, "0mm",\n');
% fprintf( fid, ['				"Y:="			, "', Ypos3_mm_string, 'mm",\n']);
% fprintf( fid, ['				"Z:="			, "', Zpos3_mm_string, 'mm"\n']);
% fprintf( fid, '			],\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLPoint",\n');
% fprintf( fid, '				"X:="			, "0mm",\n');
% fprintf( fid, ['				"Y:="			, "', Ypos5_mm_string, 'mm",\n']);
% fprintf( fid, ['				"Z:="			, "', Zpos5_mm_string, 'mm"\n']);
% fprintf( fid, '		],\n');
% fprintf( fid, '		[\n');
% fprintf( fid, '			"NAME:PolylineSegments",\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLSegment",\n');
% fprintf( fid, '				"SegmentType:="		, "Arc",\n');
% fprintf( fid, '				"StartIndex:="		, 0,\n');
% fprintf( fid, '				"NoOfPoints:="		, 3,\n');
% fprintf( fid, '				"NoOfSegments:="	, "0"\n');
% fprintf( fid, '			]\n');
% fprintf( fid, '		],\n');
% fprintf( fid, '		[\n');
% fprintf( fid, '			"NAME:PolylineXSection",\n');
% fprintf( fid, '			"XSectionType:="	, "None",\n');
% fprintf( fid, '			"XSectionOrient:="	, "Auto",\n');
% fprintf( fid, '			"XSectionWidth:="	, "0mm",\n');
% fprintf( fid, '			"XSectionTopWidth:="	, "0mm",\n');
% fprintf( fid, '			"XSectionHeight:="	, "0mm",\n');
% fprintf( fid, '			"XSectionNumSegments:="	, "0",\n');
% fprintf( fid, '			"XSectionBendType:="	, "Corner"\n');
% fprintf( fid, '		]\n');
% fprintf( fid, '	], \n');
% fprintf( fid, '	[\n');
% fprintf( fid, '		"NAME:Attributes",\n');
% fprintf( fid, ['		"Name:="		, "Polyline1_', Box_Number_String, '",\n']);
% fprintf( fid, '		"Flags:="		, "",\n');
% fprintf( fid, '		"Color:="		, "(143 175 143)",\n');
% fprintf( fid, '		"Transparency:="	, 0,\n');
% fprintf( fid, '		"PartCoordinateSystem:=", "Global",\n');
% fprintf( fid, '		"UDMId:="		, "",\n');
% fprintf( fid, '		"MaterialValue:="	, "\\"vacuum\\"",\n');
% fprintf( fid, '		"SurfaceMaterialValue:=", "\\"\\"",\n');
% fprintf( fid, '		"SolveInside:="		, True,\n');
% fprintf( fid, '		"ShellElement:="	, False,\n');
% fprintf( fid, '		"ShellElementThickness:=", "0mm",\n');
% fprintf( fid, '		"ReferenceTemperature:=", "20cel",\n');
% fprintf( fid, '		"IsMaterialEditable:="	, True,\n');
% fprintf( fid, '		"IsSurfaceMaterialEditable:=", True,\n');
% fprintf( fid, '		"UseMaterialAppearance:=", False,\n');
% fprintf( fid, '		"IsLightweight:="	, False\n');
% fprintf( fid, '	])\n');



fprintf( fid, 'oEditor.CreatePolyline(\n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:PolylineParameters",\n');
fprintf( fid, '		"IsPolylineCovered:="	, True,\n');
fprintf( fid, '		"IsPolylineClosed:="	, False,\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:PolylinePoints",\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLPoint",\n');
fprintf( fid, '				"X:="			, "0mm",\n');
fprintf( fid, ['				"Y:="			, "', Ypos1_mm_string, 'mm",\n']);
fprintf( fid, ['				"Z:="			, "', Zpos1_mm_string, 'mm"\n']);
fprintf( fid, '			],\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLPoint",\n');
fprintf( fid, '				"X:="			, "0mm",\n');
fprintf( fid, ['				"Y:="			, "', Ypos2_mm_string, 'mm",\n']);
fprintf( fid, ['				"Z:="			, "', Zpos2_mm_string, 'mm"\n']);
fprintf( fid, '			]\n');
fprintf( fid, '		],\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:PolylineSegments",\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLSegment",\n');
fprintf( fid, '				"SegmentType:="		, "Line",\n');
fprintf( fid, '				"StartIndex:="		, 0,\n');
fprintf( fid, '				"NoOfPoints:="		, 2\n');
fprintf( fid, '			]\n');
fprintf( fid, '		],\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:PolylineXSection",\n');
fprintf( fid, '			"XSectionType:="	, "None",\n');
fprintf( fid, '			"XSectionOrient:="	, "Auto",\n');
fprintf( fid, '			"XSectionWidth:="	, "0mm",\n');
fprintf( fid, '			"XSectionTopWidth:="	, "0mm",\n');
fprintf( fid, '			"XSectionHeight:="	, "0mm",\n');
fprintf( fid, '			"XSectionNumSegments:="	, "0",\n');
fprintf( fid, '			"XSectionBendType:="	, "Corner"\n');
fprintf( fid, '		]\n');
fprintf( fid, '	], \n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:Attributes",\n');
fprintf( fid, ['		"Name:="		, "Polyline2_', Box_Number_String, '",\n']);
fprintf( fid, '		"Flags:="		, "",\n');
fprintf( fid, '		"Color:="		, "(143 175 143)",\n');
fprintf( fid, '		"Transparency:="	, 0,\n');
fprintf( fid, '		"PartCoordinateSystem:=", "Global",\n');
fprintf( fid, '		"UDMId:="		, "",\n');
fprintf( fid, '		"MaterialValue:="	, "\\"vacuum\\"",\n');
fprintf( fid, '		"SurfaceMaterialValue:=", "\\"\\"",\n');
fprintf( fid, '		"SolveInside:="		, True,\n');
fprintf( fid, '		"ShellElement:="	, False,\n');
fprintf( fid, '		"ShellElementThickness:=", "0mm",\n');
fprintf( fid, '		"ReferenceTemperature:=", "20cel",\n');
fprintf( fid, '		"IsMaterialEditable:="	, True,\n');
fprintf( fid, '		"IsSurfaceMaterialEditable:=", True,\n');
fprintf( fid, '		"UseMaterialAppearance:=", False,\n');
fprintf( fid, '		"IsLightweight:="	, False\n');
fprintf( fid, '	])\n');


% fprintf( fid, 'oEditor.CreatePolyline(\n');
% fprintf( fid, '	[\n');
% fprintf( fid, '		"NAME:PolylineParameters",\n');
% fprintf( fid, '		"IsPolylineCovered:="	, True,\n');
% fprintf( fid, '		"IsPolylineClosed:="	, False,\n');
% fprintf( fid, '		[\n');
% fprintf( fid, '			"NAME:PolylinePoints",\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLPoint",\n');
% fprintf( fid, '				"X:="			, "0mm",\n');
% fprintf( fid, ['				"Y:="			, "', Ypos2_mm_string, 'mm",\n']);
% fprintf( fid, ['				"Z:="			, "', Zpos2_mm_string, 'mm"\n']);
% fprintf( fid, '			],\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLPoint",\n');
% fprintf( fid, '				"X:="			, "0mm",\n');
% fprintf( fid, ['				"Y:="			, "', Ypos4_mm_string, 'mm",\n']);
% fprintf( fid, ['				"Z:="			, "', Zpos4_mm_string, 'mm"\n']);
% fprintf( fid, '			],\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLPoint",\n');
% fprintf( fid, '				"X:="			, "0mm",\n');
% fprintf( fid, ['				"Y:="			, "', Ypos6_mm_string, 'mm",\n']);
% fprintf( fid, ['				"Z:="			, "', Zpos6_mm_string, 'mm"\n']);
% fprintf( fid, '			]\n');
% fprintf( fid, '		],\n');
% fprintf( fid, '		[\n');
% fprintf( fid, '			"NAME:PolylineSegments",\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLSegment",\n');
% fprintf( fid, '				"SegmentType:="		, "AngularArc",\n');
% fprintf( fid, '				"StartIndex:="		, 0,\n');
% fprintf( fid, '				"NoOfPoints:="		, 3,\n');
% fprintf( fid, '				"NoOfSegments:="	, "0",\n');
% fprintf( fid, ['				"ArcAngle:="		, "', num2str(dphi_deg) ,'deg",\n']);
% fprintf( fid, '				"ArcCenterX:="		, "0mm",\n');
% fprintf( fid, '				"ArcCenterY:="		, "0mm",\n');
% fprintf( fid, '				"ArcCenterZ:="		, "0mm",\n');
% fprintf( fid, '				"ArcPlane:="		, "YZ"\n');
% fprintf( fid, '			]\n');
% fprintf( fid, '		],\n');
% fprintf( fid, '		[\n');
% fprintf( fid, '			"NAME:PolylineXSection",\n');
% fprintf( fid, '			"XSectionType:="	, "None",\n');
% fprintf( fid, '			"XSectionOrient:="	, "Auto",\n');
% fprintf( fid, '			"XSectionWidth:="	, "0mm",\n');
% fprintf( fid, '			"XSectionTopWidth:="	, "0mm",\n');
% fprintf( fid, '			"XSectionHeight:="	, "0mm",\n');
% fprintf( fid, '			"XSectionNumSegments:="	, "0",\n');
% fprintf( fid, '			"XSectionBendType:="	, "Corner"\n');
% fprintf( fid, '		]\n');
% fprintf( fid, '	], \n');
% fprintf( fid, '	[\n');
% fprintf( fid, '		"NAME:Attributes",\n');
% fprintf( fid, ['		"Name:="		, "Polyline3_', Box_Number_String, '",\n']);
% fprintf( fid, '		"Flags:="		, "",\n');
% fprintf( fid, '		"Color:="		, "(143 175 143)",\n');
% fprintf( fid, '		"Transparency:="	, 0,\n');
% fprintf( fid, '		"PartCoordinateSystem:=", "Global",\n');
% fprintf( fid, '		"UDMId:="		, "",\n');
% fprintf( fid, '		"MaterialValue:="	, "\\"vacuum\\"",\n');
% fprintf( fid, '		"SurfaceMaterialValue:=", "\\"\\"",\n');
% fprintf( fid, '		"SolveInside:="		, True,\n');
% fprintf( fid, '		"ShellElement:="	, False,\n');
% fprintf( fid, '		"ShellElementThickness:=", "0mm",\n');
% fprintf( fid, '		"ReferenceTemperature:=", "20cel",\n');
% fprintf( fid, '		"IsMaterialEditable:="	, True,\n');
% fprintf( fid, '		"IsSurfaceMaterialEditable:=", True,\n');
% fprintf( fid, '		"UseMaterialAppearance:=", False,\n');
% fprintf( fid, '		"IsLightweight:="	, False\n');
% fprintf( fid, '	])\n');


% fprintf( fid, 'oEditor.CreatePolyline(\n');
% fprintf( fid, '	[\n');
% fprintf( fid, '		"NAME:PolylineParameters",\n');
% fprintf( fid, '		"IsPolylineCovered:="	, True,\n');
% fprintf( fid, '		"IsPolylineClosed:="	, False,\n');
% fprintf( fid, '		[\n');
% fprintf( fid, '			"NAME:PolylinePoints",\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLPoint",\n');
% fprintf( fid, '				"X:="			, "0mm",\n');
% fprintf( fid, ['				"Y:="			, "', Ypos2_mm_string, 'mm",\n']);
% fprintf( fid, ['				"Z:="			, "', Zpos2_mm_string, 'mm"\n']);
% fprintf( fid, '			],\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLPoint",\n');
% fprintf( fid, '				"X:="			, "0mm",\n');
% fprintf( fid, ['				"Y:="			, "', Ypos4_mm_string, 'mm",\n']);
% fprintf( fid, ['				"Z:="			, "', Zpos4_mm_string, 'mm"\n']);
% fprintf( fid, '			],\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLPoint",\n');
% fprintf( fid, '				"X:="			, "0mm",\n');
% fprintf( fid, ['				"Y:="			, "', Ypos6_mm_string, 'mm",\n']);
% fprintf( fid, ['				"Z:="			, "', Zpos6_mm_string, 'mm"\n']);
% fprintf( fid, '		],\n');
% fprintf( fid, '		[\n');
% fprintf( fid, '			"NAME:PolylineSegments",\n');
% fprintf( fid, '			[\n');
% fprintf( fid, '				"NAME:PLSegment",\n');
% fprintf( fid, '				"SegmentType:="		, "Arc",\n');
% fprintf( fid, '				"StartIndex:="		, 0,\n');
% fprintf( fid, '				"NoOfPoints:="		, 3,\n');
% fprintf( fid, '				"NoOfSegments:="	, "0"\n');
% fprintf( fid, '			]\n');
% fprintf( fid, '		],\n');
% fprintf( fid, '		[\n');
% fprintf( fid, '			"NAME:PolylineXSection",\n');
% fprintf( fid, '			"XSectionType:="	, "None",\n');
% fprintf( fid, '			"XSectionOrient:="	, "Auto",\n');
% fprintf( fid, '			"XSectionWidth:="	, "0mm",\n');
% fprintf( fid, '			"XSectionTopWidth:="	, "0mm",\n');
% fprintf( fid, '			"XSectionHeight:="	, "0mm",\n');
% fprintf( fid, '			"XSectionNumSegments:="	, "0",\n');
% fprintf( fid, '			"XSectionBendType:="	, "Corner"\n');
% fprintf( fid, '		]\n');
% fprintf( fid, '	], \n');
% fprintf( fid, '	[\n');
% fprintf( fid, '		"NAME:Attributes",\n');
% fprintf( fid, ['		"Name:="		, "Polyline3_', Box_Number_String, '",\n']);
% fprintf( fid, '		"Flags:="		, "",\n');
% fprintf( fid, '		"Color:="		, "(143 175 143)",\n');
% fprintf( fid, '		"Transparency:="	, 0,\n');
% fprintf( fid, '		"PartCoordinateSystem:=", "Global",\n');
% fprintf( fid, '		"UDMId:="		, "",\n');
% fprintf( fid, '		"MaterialValue:="	, "\\"vacuum\\"",\n');
% fprintf( fid, '		"SurfaceMaterialValue:=", "\\"\\"",\n');
% fprintf( fid, '		"SolveInside:="		, True,\n');
% fprintf( fid, '		"ShellElement:="	, False,\n');
% fprintf( fid, '		"ShellElementThickness:=", "0mm",\n');
% fprintf( fid, '		"ReferenceTemperature:=", "20cel",\n');
% fprintf( fid, '		"IsMaterialEditable:="	, True,\n');
% fprintf( fid, '		"IsSurfaceMaterialEditable:=", True,\n');
% fprintf( fid, '		"UseMaterialAppearance:=", False,\n');
% fprintf( fid, '		"IsLightweight:="	, False\n');
% fprintf( fid, '	])\n');



fprintf( fid, 'oEditor.CreatePolyline(\n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:PolylineParameters",\n');
fprintf( fid, '		"IsPolylineCovered:="	, True,\n');
fprintf( fid, '		"IsPolylineClosed:="	, False,\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:PolylinePoints",\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLPoint",\n');
fprintf( fid, '				"X:="			, "0mm",\n');
fprintf( fid, ['				"Y:="			, "', Ypos2_mm_string, 'mm",\n']);
fprintf( fid, ['				"Z:="			, "', Zpos2_mm_string, 'mm"\n']);
fprintf( fid, '			],\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLPoint",\n');
fprintf( fid, '				"X:="			, "0mm",\n');
fprintf( fid, ['				"Y:="			, "', Ypos4_mm_string, 'mm",\n']);
fprintf( fid, ['				"Z:="			, "', Zpos4_mm_string, 'mm"\n']);
fprintf( fid, '			],\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLPoint",\n');
fprintf( fid, '				"X:="			, "0mm",\n');
fprintf( fid, ['				"Y:="			, "', Ypos6_mm_string, 'mm",\n']);
fprintf( fid, ['				"Z:="			, "', Zpos6_mm_string, 'mm"\n']);
fprintf( fid, '			]\n');
fprintf( fid, '		],\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:PolylineSegments",\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLSegment",\n');
fprintf( fid, '				"SegmentType:="		, "Arc",\n');
fprintf( fid, '				"StartIndex:="		, 0,\n');
fprintf( fid, '				"NoOfPoints:="		, 3,\n');
fprintf( fid, '				"NoOfSegments:="	, "0"\n');
fprintf( fid, '			]\n');
fprintf( fid, '		],\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:PolylineXSection",\n');
fprintf( fid, '			"XSectionType:="	, "None",\n');
fprintf( fid, '			"XSectionOrient:="	, "Auto",\n');
fprintf( fid, '			"XSectionWidth:="	, "0mm",\n');
fprintf( fid, '			"XSectionTopWidth:="	, "0mm",\n');
fprintf( fid, '			"XSectionHeight:="	, "0mm",\n');
fprintf( fid, '			"XSectionNumSegments:="	, "0",\n');
fprintf( fid, '			"XSectionBendType:="	, "Corner"\n');
fprintf( fid, '		]\n');
fprintf( fid, '	], \n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:Attributes",\n');
fprintf( fid, ['		"Name:="		, "Polyline3_', Box_Number_String, '",\n']);
fprintf( fid, '		"Flags:="		, "",\n');
fprintf( fid, '		"Color:="		, "(143 175 143)",\n');
fprintf( fid, '		"Transparency:="	, 0,\n');
fprintf( fid, '		"PartCoordinateSystem:=", "Global",\n');
fprintf( fid, '		"UDMId:="		, "",\n');
fprintf( fid, '		"MaterialValue:="	, "\\"vacuum\\"",\n');
fprintf( fid, '		"SurfaceMaterialValue:=", "\\"\\"",\n');
fprintf( fid, '		"SolveInside:="		, True,\n');
fprintf( fid, '		"ShellElement:="	, False,\n');
fprintf( fid, '		"ShellElementThickness:=", "0mm",\n');
fprintf( fid, '		"ReferenceTemperature:=", "20cel",\n');
fprintf( fid, '		"IsMaterialEditable:="	, True,\n');
fprintf( fid, '		"IsSurfaceMaterialEditable:=", True,\n');
fprintf( fid, '		"UseMaterialAppearance:=", False,\n');
fprintf( fid, '		"IsLightweight:="	, False\n');
fprintf( fid, '	])\n');


fprintf( fid, 'oEditor.CreatePolyline(\n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:PolylineParameters",\n');
fprintf( fid, '		"IsPolylineCovered:="	, True,\n');
fprintf( fid, '		"IsPolylineClosed:="	, False,\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:PolylinePoints",\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLPoint",\n');
fprintf( fid, '				"X:="			, "0mm",\n');
fprintf( fid, ['				"Y:="			, "', Ypos5_mm_string, 'mm",\n']);
fprintf( fid, ['				"Z:="			, "', Zpos5_mm_string, 'mm"\n']);
fprintf( fid, '			],\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLPoint",\n');
fprintf( fid, '				"X:="			, "0mm",\n');
fprintf( fid, ['				"Y:="			, "', Ypos6_mm_string, 'mm",\n']);
fprintf( fid, ['				"Z:="			, "', Zpos6_mm_string, 'mm"\n']);
fprintf( fid, '			]\n');
fprintf( fid, '		],\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:PolylineSegments",\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PLSegment",\n');
fprintf( fid, '				"SegmentType:="		, "Line",\n');
fprintf( fid, '				"StartIndex:="		, 0,\n');
fprintf( fid, '				"NoOfPoints:="		, 2\n');
fprintf( fid, '			]\n');
fprintf( fid, '		],\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:PolylineXSection",\n');
fprintf( fid, '			"XSectionType:="	, "None",\n');
fprintf( fid, '			"XSectionOrient:="	, "Auto",\n');
fprintf( fid, '			"XSectionWidth:="	, "0mm",\n');
fprintf( fid, '			"XSectionTopWidth:="	, "0mm",\n');
fprintf( fid, '			"XSectionHeight:="	, "0mm",\n');
fprintf( fid, '			"XSectionNumSegments:="	, "0",\n');
fprintf( fid, '			"XSectionBendType:="	, "Corner"\n');
fprintf( fid, '		]\n');
fprintf( fid, '	], \n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:Attributes",\n');
fprintf( fid, ['		"Name:="		, "Polyline4_', Box_Number_String, '",\n']);
fprintf( fid, '		"Flags:="		, "",\n');
fprintf( fid, '		"Color:="		, "(143 175 143)",\n');
fprintf( fid, '		"Transparency:="	, 0,\n');
fprintf( fid, '		"PartCoordinateSystem:=", "Global",\n');
fprintf( fid, '		"UDMId:="		, "",\n');
fprintf( fid, '		"MaterialValue:="	, "\\"vacuum\\"",\n');
fprintf( fid, '		"SurfaceMaterialValue:=", "\\"\\"",\n');
fprintf( fid, '		"SolveInside:="		, True,\n');
fprintf( fid, '		"ShellElement:="	, False,\n');
fprintf( fid, '		"ShellElementThickness:=", "0mm",\n');
fprintf( fid, '		"ReferenceTemperature:=", "20cel",\n');
fprintf( fid, '		"IsMaterialEditable:="	, True,\n');
fprintf( fid, '		"IsSurfaceMaterialEditable:=", True,\n');
fprintf( fid, '		"UseMaterialAppearance:=", False,\n');
fprintf( fid, '		"IsLightweight:="	, False\n');
fprintf( fid, '	])\n');
fprintf( fid, 'oEditor = oDesign.SetActiveEditor("3D Modeler")\n');
fprintf( fid, 'oEditor.Unite(\n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:Selections",\n');
fprintf( fid, ['		"Selections:="		, "Polyline1_', Box_Number_String, ',Polyline2_', Box_Number_String,',Polyline3_', Box_Number_String,',Polyline4_', Box_Number_String,'"\n']);
fprintf( fid, '	], \n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:UniteParameters",\n');
fprintf( fid, '		"KeepOriginals:="	, False,\n');
fprintf( fid, '		"TurnOnNBodyBoolean:="	, True\n');
fprintf( fid, '	])\n');
fprintf( fid, 'oEditor.CoverLines(\n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:Selections",\n');
fprintf( fid, ['		"Selections:="		, "Polyline1_', Box_Number_String,'",\n']);
fprintf( fid, '		"NewPartsModelFlag:="	, "Model"\n');
fprintf( fid, '	])\n');
fprintf( fid, 'oEditor.ThickenSheet(\n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:Selections",\n');
fprintf( fid, ['		"Selections:="		, "Polyline1_', Box_Number_String,'",\n']);
fprintf( fid, '		"NewPartsModelFlag:="	, "Model"\n');
fprintf( fid, '	], \n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:SheetThickenParameters",\n');
fprintf( fid, ['		"Thickness:="		, "', num2str(Zsize),'",\n']);
fprintf( fid, '		"BothSides:="		, True,\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:ThickenAdditionalInfo",\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:ShellThickenDirectionInfo",\n');
fprintf( fid, '				"SampleFaceID:="	, 37,\n');
fprintf( fid, '				"ComponentSense:="	, True,\n');
fprintf( fid, '				[\n');
fprintf( fid, '					"NAME:PointOnSampleFace",\n');
fprintf( fid, '					"X:="			, "3.54994185728112e-16mm",\n');
fprintf( fid, '					"Y:="			, "0.616783372363864mm",\n');
fprintf( fid, '					"Z:="			, "0.488478523742559mm"\n');
fprintf( fid, '				],\n');
fprintf( fid, '				[\n');
fprintf( fid, '					"NAME:DirectionAtPoint",\n');
fprintf( fid, '					"X:="			, "1mm",\n');
fprintf( fid, '					"Y:="			, "-5.80685407811105e-16mm",\n');
fprintf( fid, '					"Z:="			, "-2.74523708024267e-16mm"\n');
fprintf( fid, '				]\n');
fprintf( fid, '			]\n');
fprintf( fid, '		]\n');
fprintf( fid, '	])\n');


%% Change Color

fprintf( fid, 'oEditor.ChangeProperty(\n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:AllTabs",\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:Geometry3DAttributeTab",\n');
fprintf( fid, '			[');
fprintf( fid, '				"NAME:PropServers", \n');
fprintf( fid, ['				"Polyline1_', Box_Number_String,'"\n']);
fprintf( fid, '			],\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:ChangedProps",\n');
fprintf( fid, '				[\n');
fprintf( fid, '					"NAME:Color",\n');
fprintf( fid, ['					"R:="			, ', cii1,',\n']);
fprintf( fid, ['					"G:="			, ',  cii2,',\n']);
fprintf( fid, ['					"B:="			, ',   cii3,'\n']);
fprintf( fid, '				]\n');
fprintf( fid, '			]\n');
fprintf( fid, '		]\n');
fprintf( fid, '	])\n');



%% Change Permittivity

if ~Previously_Defined_Material_in(idx)

    Previously_Defined_Material_in(idx) = 1;

    % Define New Permittivity

    fprintf( fid, 'oDefinitionManager = oProject.GetDefinitionManager()\n');
    fprintf( fid, 'oDefinitionManager.AddMaterial(\n');
    fprintf( fid, '	[\n');

    fprintf( fid, '		"NAME:MaterialBox');
    % fprintf( fid, Box_Number_String);
    fprintf( fid, num2str(idx));
    fprintf( fid, '",\n');
    fprintf( fid, '		"CoordinateSystemType:=", "Cartesian",\n');
    fprintf( fid, '		"BulkOrSurfaceType:="	, 1,\n');
    fprintf( fid, '		[\n');
    fprintf( fid, '			"NAME:PhysicsTypes",\n');
    fprintf( fid, '			"set:="			, ["Electromagnetic"]\n');
    fprintf( fid, '		],\n');
    fprintf( fid, '		"permittivity:="	, "');
    fprintf( fid, num2str( Permittivity ));
    fprintf( fid, '",\n');

    fprintf( fid, '		"dielectric_loss_tangent:=", "');
    fprintf( fid, num2str(Loss_Tangent));
    fprintf( fid, '"\n');
    fprintf( fid, '	])\n');

end

fprintf( fid, 'oEditor.ChangeProperty(\n');
fprintf( fid, '	[\n');
fprintf( fid, '		"NAME:AllTabs",\n');
fprintf( fid, '		[\n');
fprintf( fid, '			"NAME:Geometry3DAttributeTab",\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:PropServers", \n');
fprintf( fid, '				"Polyline1_');
fprintf( fid, Box_Number_String);
fprintf( fid, '"\n');

fprintf( fid, '			],\n');
fprintf( fid, '			[\n');
fprintf( fid, '				"NAME:ChangedProps",\n');
fprintf( fid, '				[\n');
fprintf( fid, '					"NAME:Material",\n');
fprintf( fid, '					"Value:="		, "\\"MaterialBox');
% fprintf( fid, Box_Number_String);
fprintf( fid, num2str(idx));

fprintf( fid, '\\""\n');
fprintf( fid, '				]\n');
fprintf( fid, '			]\n');
fprintf( fid, '		]\n');
fprintf( fid, '	])\n');


% Pass it to the next loop
Previously_Defined_Material_out = Previously_Defined_Material_in;


end